<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8KCBSMA" name="C:/Users/USER/IdeaProjects/SwagLabsProject" tests="14" failures="2" timestamp="27 Mar 2023 16:55:41 GMT" time="35.381" errors="0">
  <testcase name="Login" time="2.235" classname="Testing.LoginTest"/>
  <testcase name="Login" time="6.024" classname="Testing.LoginTest">
    <failure type="java.lang.AssertionError" message="Login failed">
      <![CDATA[java.lang.AssertionError: Login failed
	at org.testng.Assert.fail(Assert.java:89)
	at Testing.LoginTest.Login(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase>
  <testcase name="Login" time="5.667" classname="Testing.LoginTest">
    <failure type="java.lang.AssertionError" message="Login failed">
      <![CDATA[java.lang.AssertionError: Login failed
	at org.testng.Assert.fail(Assert.java:89)
	at Testing.LoginTest.Login(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1031)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase>
  <testcase name="Login" time="6.838" classname="Testing.LoginTest"/>
  <testcase name="FLogin" time="0.971" classname="Testing.LoginTest"/>
  <testcase name="AddToCart" time="0.243" classname="Testing.HomepgTest"/>
  <testcase name="CheckCart" time="0.139" classname="Testing.HomepgTest"/>
  <testcase name="RemoveProduct" time="0.202" classname="Testing.CartpgTest"/>
  <testcase name="CheckOut" time="0.268" classname="Testing.CartpgTest"/>
  <testcase name="AddIncorrectInfo" time="1.293" classname="Testing.CheckoutpgTest"/>
  <testcase name="AddIncorrectInfo" time="1.474" classname="Testing.CheckoutpgTest"/>
  <testcase name="AddIncorrectInfo" time="1.172" classname="Testing.CheckoutpgTest"/>
  <testcase name="AddCorrectInfo" time="0.902" classname="Testing.CheckoutpgTest"/>
  <testcase name="GetInfo" time="0.515" classname="Testing.FinishpgTest"/>
</testsuite>
